package WinJava.WebView;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import userclasses.StateMachine;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.components.ImageViewer;
import com.codename1.components.WebBrowser;
import com.codename1.javascript.JSFunction;
import com.codename1.javascript.JSObject;
import com.codename1.javascript.JavascriptContext;
import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Container;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.util.Resources;

import java.util.Iterator;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class WebView extends Container {
    private BrowserComponent browser;
	private JavascriptContext c;
    private Form current; 
    private Resources theme;

    public void init(Object context) {
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Log.bindCrashProtection(true);
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        
        Form f = new Form("WebView", new BorderLayout());
        // this.setLayout(new BorderLayout());
        WebBrowser b = new WebBrowser();
        
        browser = (BrowserComponent)b.getInternal();
        c = new JavascriptContext(browser);
        b.setURL("https://www.codenameone.com/");
        
        f.add(BorderLayout.CENTER, b);
        
        f.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }
}
